sudo: false
language: java

jdk:
- openjdk8

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
    - autoconf
    - automake
    - libtool
    - curl
    - make
    - g++
    - unzip

before_install:
  - ./install-protobuf.sh
