sudo: false
language: java

jdk:
- openjdk8

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
    - unzip

before_install:
  - chmod +x ./install-protobuf.sh
  - ./install-protobuf.sh
  - chmod +x ./protobuf/bin/protoc

install:
  - mvn install -DprotocExecutable="./protobuf/bin/protoc" -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -DprotocExecutable="./protobuf/bin/protoc" -B
