dist: trusty
sudo: false
language: java

jdk:
- openjdk8

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
    - unzip

before_install:
  - chmod +x ./.travis/install-protobuf.sh
  - ./.travis/install-protobuf.sh
  - chmod +x $HOME/protobuf/bin/protoc
  - export PATH=$PATH:$HOME/protobuf/bin

after_success:
  - mvn clean test jacoco:report coveralls:report
