sudo: false
language: java

jdk:
- openjdk8

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
    - unzip

before_install:
  - chmod +x ./install-protobuf.sh
  - ./install-protobuf.sh
  - chmod +x ./protobuf/bin/protoc
  - PATH=./protobuf/bin:$PATH
