name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Sources Checkout
        uses: actions/checkout@v1
      
      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Set up Protobuf
        run: |
          chmod +x ./.travis/install-protobuf.sh
          ./.travis/install-protobuf.sh
          
      - name: Update env
        run: |
          chmod +x $HOME/protobuf/bin/protoc
          echo "::add-path::$HOME/protobuf/bin"
        shell: bash
            
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package
